#!/bin/bash

# Determine if arg is file and is readable

# File exist and is readble
if [[ -f "$1" && -r "$1" ]]; then
    echo "File exist and is readable"
    exit 0
fi

# 1st arg contains no characters
if [[ -z "$1" || "$1" == "--help" ]]; then
    echo "Usage: $0 <filename>"
    exit 0
fi

# Arg passed is not a file
if [[ ! -f "$1" ]]; then
    echo "Not a file: $1"
    exit 1
fi 
