#!/bin/bash

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <fruit>" >&2
    exit 1
fi
case $1 in
        "apple")
            echo "Apples are red"
	    ;;
        "banana")
            echo "Bananas are yellow"
	    ;;
        "kiwi")
            echo "Kiwis are brown/green"
            ;;
        *)
            echo "Error: $1 is an unkown fruit"
            exit 1
	    ;;
esac
